#! /bin/sh
#  /etc/init.d/kikibot

### BEGIN INIT INFO
# Provides:          kikibot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the Kikibot service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   Julian Thijssen <Nimthora[AT]gmail.com>
# Date:     14/03/2017

NAME="kikibot"
DESC="Kikibot service"

# The path to Jsvc
EXEC="/usr/bin/jsvc"

# The path to the folder containing Kikibot.jar
FILE_PATH="/home/$NAME"

# The path to the folder containing the java runtime
JAVA_HOME="/usr/lib/jvm/default-java"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/Kikibot.jar:$FILE_PATH/libs/commons-daemon-1.0.15/commons-daemon-1.0.15.jar:$FILE_PATH/libs/sqlite-jdbc-3.15.1.jar"

# The fully qualified name of the class to execute
CLASS="bot.DaemonBot"

# Any command line arguments to be passed to the our Java Daemon implementations init() method 
ARGS=""

#The user to run the daemon as
USER="root"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="$FILE_PATH/log/$NAME.out"

# System.err writes to this file...
LOG_ERR="$FILE_PATH/err/$NAME.err"

jsvc_exec()
{   
    cd $FILE_PATH
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -cwd $FILE_PATH -Xss1280k -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)  
        echo "Starting the $DESC..."        
        
        # Start the service
        jsvc_exec
        
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."
        
        # Stop the service
        jsvc_exec "-stop"       
        
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "Restarting the $DESC..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac